### ISSUE TITLE
tty.Open() suspends process when in background (linux)

### ISSUE THREAD

**Issue by ThisGuyCodes** [mattn/go-tty#26]
`tty.Open()` causes the calling process to suspend with `SIGTTOU` on Linux if the caller is not in the foreground. Specifically the ioctl termios write is what hangs.

Ideally this would instead return an error.

I attempted a prototype to catch this signal with `signal.Notify()` but it seems the signal isn't actually being sent until the process is in the foreground? Not sure.

Alternatively is there a way to predict that this will happen? Some way of reading if the process is in the foreground?

**Comment by mattn** [comment]
Can you provide small code reproducible?

**Comment by ThisGuyCodes** [comment]
```Go
package main

import "github.com/mattn/go-tty"

func main() {
	tty.Open()
}
```

`go run main.go &`

**Comment by mattn** [comment]
Probably, it's not issue of go-tty, but if you want to run tasks in background, how about to ignore the signal?

```
 signal.Ignore(syscall.SIGTTOU)
```

**Comment by ThisGuyCodes** [comment]
On second thought, maybe it makes more sense for the calling process to be responsible for this.

I will say that it's not intuitive that `Open()` writes to the tty config.
