### ISSUE TITLE
Break after ctrl+C

### ISSUE THREAD

**Issue by nwtgck** [mattn/go-tty#37]
Hi,

Thank you very much for your project. I make a simple program using go-tty as follows.

```go
func main() {
	tty, err := tty.Open()
	if err != nil {
		log.Fatal(err)
	}
	defer tty.Close()
	s, err := tty.ReadString()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(s)
}
```

After I typed <kbd>ctrl</kbd>+<kbd>C</kbd>, my prompt is broken. My environment is macOS.

![go-tty-broken-prompt mp4 opt](https://user-images.githubusercontent.com/10933561/79067523-e098cd00-7cfa-11ea-987b-583347caee86.gif)

**Comment by mattn** [comment]
You have to catch os.Interupt.
